# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Terra:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
     contents: read
     id-token: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.9.6

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

     - name: Terraform Init
       run: terraform init

     - name: Terraform Plan
       run: terraform plan -out=tfplan.out -var "slack_webhook=${{ secrets.SLACK_WEBHOOK }}"
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

     - name: Terraform Apply (auto-approve)
       if: github.ref == 'refs/heads/main'
       run:  terraform apply "tfplan.out"
   
